// Code generated by "stringer -type=TileType -linecomment -output=stringers.go"; DO NOT EDIT.

package gridspech

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[TypeHole-0]
	_ = x[TypeBlank-1]
	_ = x[TypeEnd-2]
	_ = x[TypeKing-3]
	_ = x[TypeMine1-4]
	_ = x[TypeMine2-5]
	_ = x[TypeMine3-6]
	_ = x[TypeJoin1-7]
}

const _TileType_name = "_BlankEndKingMine1Mine2Mine3Join1"

var _TileType_index = [...]uint8{0, 1, 6, 9, 13, 18, 23, 28, 33}

func (i TileType) String() string {
	if i >= TileType(len(_TileType_index)-1) {
		return "TileType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TileType_name[_TileType_index[i]:_TileType_index[i+1]]
}
