// Code generated by "stringer -type=TileType,TileColor -linecomment -output=stringers.go"; DO NOT EDIT.

package gridspech

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[TypeHole-0]
	_ = x[TypeBlank-1]
	_ = x[TypeGoal-2]
	_ = x[TypeCrown-3]
	_ = x[TypeDot1-4]
	_ = x[TypeDot2-5]
	_ = x[TypePlus-6]
}

const _TileType_name = "HoleBlankGoalCrownDot1Dot2Plus"

var _TileType_index = [...]uint8{0, 4, 9, 13, 18, 22, 26, 30}

func (i TileType) String() string {
	if i >= TileType(len(_TileType_index)-1) {
		return "TileType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TileType_name[_TileType_index[i]:_TileType_index[i+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ColorNone-0]
	_ = x[ColorA-1]
	_ = x[ColorB-2]
}

const _TileColor_name = "AB"

var _TileColor_index = [...]uint8{0, 0, 1, 2}

func (i TileColor) String() string {
	if i >= TileColor(len(_TileColor_index)-1) {
		return "TileColor(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TileColor_name[_TileColor_index[i]:_TileColor_index[i+1]]
}
