// Code generated by "stringer -type=TileType -linecomment -output=stringers.go"; DO NOT EDIT.

package gridspech

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[TypeHole-0]
	_ = x[TypeBlank-1]
	_ = x[TypeGoal-2]
	_ = x[TypeCrown-3]
	_ = x[TypeDot1-4]
	_ = x[TypeDot2-5]
	_ = x[TypeDot3-6]
	_ = x[TypeJoin1-7]
	_ = x[TypeJoin2-8]
}

const _TileType_name = "_BlankGoalCrownDot1Dot2Dot3Join1Join2"

var _TileType_index = [...]uint8{0, 1, 6, 10, 15, 19, 23, 27, 32, 37}

func (i TileType) String() string {
	if i >= TileType(len(_TileType_index)-1) {
		return "TileType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TileType_name[_TileType_index[i]:_TileType_index[i+1]]
}
